themes = {
    "template": ["link to background", "author color", "quote color"],
    "default": ["assets/background assets/default.jpg", "#5296f0", "#151515"],
    "dark": ["assets/background assets/dark.jpg", "#dadada", "#9f9f9f"],
    "radical": ["assets/background assets/radical.jpg", "#a9fef7", "#fc428d"],
    "merko": ["assets/background assets/merko.jpg", "#FFF", "#90b302"],
    "gruvbox": ["assets/background assets/gruvbox.jpg", "#89b978", "#f8bc2f"],
    "tokyonight": ["assets/background assets/tokyonight.jpg", "#38bdae", "#6da0f6"],
    "synthwave": ["assets/background assets/synthwave.jpg", "#be2689", "#dde3e7"], #
    "highcontrast": ["assets/background assets/highcontrast.jpg", "#FFF", "#c1cb12"],
    "dracula": ["assets/background assets/dracula.jpg", "#f8f8f2", "#ff6e96"],
    "prussian": ["assets/background assets/prussian.jpg", "#6e93b5", "#a2c3e1"],
    "monokai": ["assets/background assets/monokai.jpg", "#f1f1eb", "#eb1f6a"],
    "vue": ["assets/background assets/vue.jpg", "#273849", "#5fc396"],
    "vue-dark": ["assets/background assets/vue-dark.jpg", "#fffefe", "#5fc396"],
    "shades-of-purple": ["assets/background assets/shades-of-purple.jpg", "#d9b50e", "#a599e9"],
    "nightowl": ["assets/background assets/nightowl.jpg", "#a77dcb", "#7fdbca"],
    "buefy": ["assets/background assets/buefy.jpg", "#8d71db", "#8d71db"],
    "blue-green": ["assets/background assets/blue-green.jpg", "#2780a4", "#0cf574"],
    "algolia": ["assets/background assets/algolia.jpg", "#0194dd", "#ffffff"],
    "great-gatsby": ["assets/background assets/great-gatsby.jpg", "#d68c1f", "#ffd95b"],
    "darcula": ["assets/background assets/darcula.jpg", "#a15619", "#bebebe"],
    "bear": ["assets/background assets/bear.jpg", "#c13879", "#c13879"],
    "solarized-dark": ["assets/background assets/solarized-dark.jpg", "#859900", "#1f7bb9"],
    "solarized-light": ["assets/background assets/solarized-light.jpg", "#489cd5", "#859900"],
    "chartreuse-dark": ["assets/background assets/chartreuse-dark.jpg", "#6ad600", "#ffffff"],
    "nord": ["assets/background assets/nord.jpg", "#748fac", "#748fac"],
    "gotham": ["assets/background assets/gotham.jpg", "#258f76", "#99d1ce"],
    "material-palenight": ["assets/background assets/material-palenight.jpg", "#ae81ce", "#a6accd"],
    "graywhite": ["assets/background assets/vision-friendly-dark.jpg", "#464a4e", "#24292e"],
    "vision-friendly-dark": ["assets/background assets/vision-friendly-dark.jpg", "#d69300", "#d69300"],
    "ayu-light": ["assets/background assets/ayu-light.jpg", "#d2b270", "#c7c8c2"],
    "midnight-purple": ["assets/background assets/midnight-purple.jpg", "#7e3ace", "#ffffff"],
    "calm": ["assets/background assets/calm.jpg", "#c5705d", "#ebcfb2"],
    "flag-india": ["assets/background assets/flag-india.jpg", "#ffa040", "#509e2f"],
    "omni": ["assets/background assets/omni.jpg", "#da68ab", "#e1e1e6"],
    "react": ["assets/background assets/react.jpg", "#56bcd9", "#e3be79"],
    "jolly": ["assets/background assets/jolly.jpg", "#dd58c1", "#ffffff"],
    "maroongold": ["assets/background assets/maroongold.jpg", "#d5c974", "#e0aa3e"],
    "yeblu": ["assets/background assets/yeblu.jpg", "#d6db0b", "#ffffff"],
    "blueberry": ["assets/background assets/blueberry.jpg", "#7395df", "#27e8a7"],
    "slateorange": ["assets/background assets/slateorange.jpg", "#db942a", "#ffffff"],
    "kacho_ga": ["assets/background assets/kacho-ga.jpg", "#aa453a", "#aa453a"],
    "city_light": ["assets/background assets/city_light.jpg", "#4f94ef", "#434d58"],
    "swift": ["assets/background assets/swift.jpg", "#272727", "#000000"],
}
